### ISSUE TITLE
CPAN::PackageDetails is not indexed correctly

### ISSUE THREAD

**Issue by chorny** [briandfoy/cpan-packagedetails#8]
CPAN::PackageDetails in 02packages.details.txt is from previous version of distribution - CPAN-PackageDetails-0.261.tar.gz, but there is a new version - CPAN-PackageDetails-0.262.tar.gz.

Probably because PAUSE could not understand "BEGIN { $VERSION = '0.262' }".

02packages.details.txt:
```
CPAN::PackageDetails              0.261  B/BD/BDFOY/CPAN-PackageDetails-0.261.tar.gz
CPAN::PackageDetails::Entries     0.261  B/BD/BDFOY/CPAN-PackageDetails-0.262.tar.gz
```

**Comment by briandfoy** [comment]
Yep, that was it.

For those playing at home, PAUSE's indexer determines the version by looking for a line with just a `$VERSION` assignment. This is static analysis and doesn't run anything but that one line. This doesn't work:

    BEGIN { $VERSION = '0.262' }

But this does:

```
BEGIN { 
$VERSION = '0.263' 
}
```
